---
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: cd frontend && npm install
      - run: cd frontend && npm run build
      - run: cd backend && npm install
  
  deploy:
    docker:
      - image: stackbuilders/hapistrano:latest
    steps:
      - checkout
      - run: echo -e "Host * \n  StrictHostKeyChecking no" >> ~/.ssh/config
      - run:
          name: Deploy to staging
          no_output_timeout: 30m
          command: hap deploy -c deploy/cloud.yaml        

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

