---
- name: Set a hostname
  hostname:
    name: "sandbox"

- name: add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost sandbox'
    state: present

- name: Install packages
  apt: name={{ item }} state=present
  with_items:
    - git
    - htop
    - nmap
    - strace
    - tmux
    - net-tools  
    - vim

- name: Open ssh port
  ufw:
    rule: allow
    port: '{{ item }}'
  with_items:
    - 22
    - 80
    - 443  

- name: Start service nginx, if not running
  service:
    name: nginx
    state: started
